messages:
  voicechat_warning: "To use the voice mod, you must be at least 13 years old. We aim to moderate the server but cannot always be vigilante. Some other players may say words you might find offensive."
